---
- name: Copy theme
  copy: src=csg_greeter_theme/ dest=/usr/share/lightdm-webkit/themes/csg owner=root group=root mode=ugo+rX

- name: Correct permissions on theme folder
  file: path=/usr/share/lightdm-webkit/themes/csg owner=root group=root mode=0755
