---
- name: Create CSG's .ssh
  file: path=/home/csg/.ssh state=directory owner=csg group=csg mode=0700

- name: Install authorized_keys
  copy: src=authorized_keys dest=/home/csg/.ssh/authorized_keys owner=csg group=csg mode=0600
