---
- name: Install Software
  xbps:
    name: "{{ software }}"
    state: present

- name: Make csg member of useful groups
  user: name=csg group={{ item }} append=yes
  with_items:
    - vboxusers
    - wireshark

- name: Remove nm-applet autostart
  file: path=/etc/xdg/autostart/nm-applet.desktop state=absent
