---
- name: Install Software
  xbps: pkg="{{ item }}" state=present
  with_items: "{{ software }}"

- name: Make csg member of useful groups
  user: name=csg group={{ item }} append=yes
  with_items:
    - vboxusers
    - wireshark

- name: Remove nm-applet autostart
  file: path=/etc/xdg/autostart/nm-applet.desktop state=absent

- name: Create CSG's .ssh
  file: path=/home/csg/.ssh state=directory owner=csg group=csg mode=0700

- name: Install authorized_keys
  copy: src=authorized_keys dest=/home/csg/.ssh/authorized_keys owner=csg group=csg mode=0600
