#!/bin/bash

inventory="$( dirname "${BASH_SOURCE[0]}" )/../inventory"

if [ -f "${inventory}" ] ; then
    echo "Using inventory at ${inventory}"
else
    echo "No inventory found!"
    exit 1
fi

echo "Collecting host keys"
echo "# START CSG SECTION" > /tmp/csg_hostkeys
for host in $(grep csg "${inventory}") ; do
    ssh-keyscan -t ed25519 "${host}" 2>/dev/null >> /tmp/csg_hostkeys
done
echo "# END CSG SECTION" >> /tmp/csg_hostkeys

echo "Updating ~/.ssh/known_hosts"
sed -i "/# START CSG SECTION/,/# END CSG SECTION/d" ~/.ssh/known_hosts
cat /tmp/csg_hostkeys >> ~/.ssh/known_hosts
echo "Update complete"
