---
sg_pkg_path: https://mirror.esc7.net/%m/
sg_pkg_server: mirror.esc7.net

sg_globalconf:
  hostname: csg-lab-isr.csg
  default_gateway: 10.176.169.1
  bootresolvers:
    - 10.182.70.107
    - 10.182.70.24
    - 10.180.15.160
    - 10.180.14.69
  ssh:
    permit_password: false
    listen_egress: true
  pf:
    block_policy: drop
  dns:
    SOA: 2016120100
    stubzones:
      - name: utdallas.edu
        private: true
        cidr: 10.0.0.0/8
        arpa: 10.in-addr.arpa
        addresses:
          - 10.182.70.107
          - 10.182.70.24
          - 10.180.15.160
          - 10.180.14.69
  ntp:
    clocks:
      - pool.ntp.org

sg_networks:
  - name: lab
    desc: Trusted network for lab machines
    domain: csg
    cidr: 192.168.10.0/24
    arpa: 168.192.in-addr.arpa
    attach_to: em1
    services:
      - ssh
      - jumphost
      - nat
      - dhcp
      - dns
      - ntp
      - pxeboot
    serviceconf:
      dhcp:
        pools:
          - 192.168.10.128/25
        routers: 192.168.10.1
        dns: 192.168.10.1
        ntp: 192.168.10.1
        pxeboot_fname: pxelinux.0
        pxeboot_next: 192.168.10.1
        allow_unknown: true
      dns:
        authname: csg-lab-isr.csg
        adminmail: csg.utdallas.edu
      nat:
        nat_to: em0
        mode: dhcp
        autonat:
          - 192.168.10.32/28
    hosts:
      - name: csg-lab-isr
        mac: 00:04:23:ab:4e:e5
        addr: 192.168.10.1
        dns:
          CNAME:
            - preseed
      - name: projector
        mac: 00:25:5c:6c:c6:da
        addr: 192.168.10.3
      - name: printer
        mac: 00:1b:a9:70:e5:42
        addr: 192.168.10.4
      - name: poodle
        mac: 00:21:9b:74:79:5f
        addr: 192.168.10.5
        dns:
          CNAME:
            - jukebox
      - name: drown
        mac: 00:21:9b:71:ea:61
        addr: 192.168.10.6
      - name: csg01
        mac: 00:18:8b:5a:64:52
        addr: 192.168.10.33
      - name: csg02
        mac: 00:13:72:db:73:79
        addr: 192.168.10.34
      - name: csg03
        mac: 00:18:8b:5a:92:28
        addr: 192.168.10.35
      - name: csg04
        mac: 00:18:8b:5a:68:63
        addr: 192.168.10.36
      - name: csg05
        mac: 00:18:8b:5a:68:3a
        addr: 192.168.10.37
      - name: csg06
        mac: 00:21:9b:74:60:46
        addr: 192.168.10.38
      - name: csg07
        mac: 00:21:9b:74:70:18
        addr: 192.168.10.39
      - name: csg08
        mac: 00:21:9b:74:74:ff
        addr: 192.168.10.40
      - name: csg09
        mac: 00:21:9b:74:87:33
        addr: 192.168.10.41

sg_interfaces:
  - name: em0
    desc: External UTD Network
    address: 10.176.169.16/24
  - name: em1
    desc: Internal CSG Network
    address: 192.168.10.1/24
